### ISSUE TITLE
kdtree_knn_search only works once

### ISSUE THREAD

**Issue by MedourMehdi** [begeekmyfriend/kdtree#2]
Hi,

It seems that research in the kdtree is only possible once.

see the attached test file below who results to 

```
3 nearest neighbors of sample(-1.00, -5.00):
(1.24, -2.86) Distance:3.097935
(-2.96, -0.50) Distance:4.908319
(-6.88, -5.40) Distance:5.893590
3 nearest neighbors of sample(-8.00, -7.00):
(1.24, -2.86) Distance:3.097935
(-2.96, -0.50) Distance:4.908319
(-6.88, -5.40) Distance:5.893590
```

Whatever the next values you add in the code for searching, the result is the same.

[kdtree_test.c.zip](https://github.com/begeekmyfriend/kdtree/files/12506590/kdtree_test.c.zip)

Regards

**Comment by begeekmyfriend** [comment]
Sir,

I am not sure whether I have made meself clear or not in the README file. The kdtree has to be rebuilt every time when there is any change on the nodes. It means you cannot add or remove any node dynamically in a built kdtree and go on searching. The thought of implementation link has been put in the README that you can refer to.

Thanks

**Comment by MedourMehdi** [comment]
Hi,

Thanks for the reply.

Yes it's not very clear as even if I rebuild the tree (via the rebuild function) the search result is the same.
So the question is how to make more than one research in the tree?

`        

        kdtree_insert(tree, sample13); 
        /* All my nodes were added here, before the rebuild of the tree */                
        kdtree_rebuild(tree);
                
        kdtree_dump(tree);
                  
        int k = 3;
        double target[] = { -1, -5 };
        kdtree_knn_search(tree, target, k);
...
/* -> Result x is ok */

        kdtree_knn_dump(tree);
        
        kdtree_rebuild(tree); /* As indicated in the readme I rebuild the tree again in order to make a new search */
        
        double target1[] = { -8, -7 };
        kdtree_knn_search(tree, target1, k);   
...
/* Result x is nok despite the rebuild */`

Many thanks.

**Comment by begeekmyfriend** [comment]
Sir,

Thank you for reaching out. You have found the bug in this project. Yes, in order to support multiple search, we need to call both `knn_list_clear` and `coord_passed_reset` functions on each search to clean up the trace left behind the last one. I have patched it up. Now it works for you.

By the way, the rebuild function can be called only if there is any sample change. For multiple search, no need to call it at all.

Many thanks as well.

```shell
(6.27,5.50)
+-------(17.05,-12.79)
|       +-------(10.80,-5.03)
|       |       +-------(14.63,-0.35)
|       |       +-------(7.83,15.70)
|       +-------(7.75,-22.68)
|               +-------(15.31,-13.16)
+-------(1.24,-2.86)
        +-------(-2.96,-0.50)
        |       +-------(1.75,12.26)
        |       +-------(-4.96,12.61)
        +-------(-6.88,-5.40)
                +-------(-4.60,-10.55)
3 nearest neighbors of sample(-1.00, -5.00):
(1.24, -2.86) Distance:3.097935
(-2.96, -0.50) Distance:4.908319
(-6.88, -5.40) Distance:5.893590
3 nearest neighbors of sample(-8.00, -7.00):
(-6.88, -5.40) Distance:1.953049
(-4.60, -10.55) Distance:4.915537
(-2.96, -0.50) Distance:8.225059
```

**Comment by MedourMehdi** [comment]
Great! My pleasure. Thank you for your responsiveness.
